# Generated by Django 5.0.2 on 2024-02-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Drink', 'Drink'), ('fruit', 'fruit'), ('vegetable', 'vegetable'), ('meat', 'meat'), ('dairy', 'dairy'), ('beverage', 'beverage')], max_length=255),
        ),
    ]
